kind: pipeline
type: kubernetes
name: default

metadata:
    namespace: drone

steps:
    - name: build-docker
      image: plugins/docker
      when:
          branch:
              - main
          event:
              include:
                  - push
                  - tag
      settings:
          repo: ghcr.io/ierdna100/minecraftserverbot
          registry: ghcr.io
          tags:
              #- ${DRONE_TAG}
              - latest
          username: ierdna100
          password:
              from_secret: github-token

trigger:
    branch:
        - main
